name: IOT BRIDGE

on:
  push:
    branches: [ "test_submodule" ]
  pull_request:
    branches: [ "test_submodule" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test command 1
      run: echo "test-job-1"
      shell: bash

  test-job-2:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
    - name: Test command 2
      run: echo "test-job-2"
      shell: bash

  build:
    needs: test-job-2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.4, 3.10, 3.9, 3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        # pip install -e .
        # pip install -r ./thirdparty.sdv_testing_tool/requirements.txt
        # pytest -m "component"
        echo 1
    