name: IOT BRIDGE

on:
  push:
    branches: [ "test_submodule" ]
  pull_request:
    branches: [ "test_submodule" ]

jobs:
  component-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Component Testing
      run: |
        echo "component tests running..."
        echo "component tests done."
        # pytest -m "component"
      shell: bash

  integration-testing:
    needs: component-testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Integration Testing
      run: |
        echo "integration tests running..."
        echo "integration tests done."
        # pytest -m "integration"
      shell: bash

  system-testing:
    needs: integration-testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: System Testing
      run: |
        echo "system tests running..."
        echo "system tests done."
        # pytest -m "system"
      shell: bash

  build:
    needs: system-testing
    runs-on: ubuntu-latest
    steps:
    - name: checkout all the submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Test with pytest
      run: |
        pip install -r ./thirdparty/sdv_testing_tool/requirements.txt
        echo 1
    